title: Urvik Patel 
logo: urvik1.jpg
description: >
  👋 Hi, I'm Urvik — a Data Analyst and AI Engineer passionate about solving real-world problems with data. 
  With hands-on experience in government, healthcare, and environmental analytics, I specialize in creating impactful dashboards, automating pipelines, and deploying AI/ML solutions. 
  Currently pursuing my Master of Information Technology (AI) at the University of Melbourne.
  
show_downloads: true
theme: jekyll-theme-minimal
